# Generated by Django 5.1.1 on 2025-07-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivered',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('oldindan', 'Oldindan to‘lov'), ('olgandan', 'Olgandan so‘ng to‘lov')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
    ]
