# Generated by Django 5.1.1 on 2025-07-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_order_delivered_order_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
