# Generated by Django 5.1.1 on 2025-07-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_banner_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', 'Buyurtma berildi'), ('preparing', 'Tayyorlanmoqda'), ('shipped', 'Yuborildi'), ('delivered', 'Yetib keldi'), ('done', 'Yakunlandi')], default='ordered', max_length=20),
        ),
    ]
